config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  resources :users do
    resources :photos
  end

  resources :photos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fuck_tags_fuck_everything.rb
class FuckTagsFuckEverything < ApplicationRecord
  belongs_to :photo
  belongs_to :tag
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_one_attached :image_file

  # this has many needs to be the literal name of the table
  has_many :fuck_tags_fuck_everything
  has_many :tags, :through => :fuck_tags_fuck_everything


  # this is a special method!! very useful!!
  scope :lilbub, -> {where(title:"Lil Bub!")}


end

app/models/tag.rb
class Tag < ApplicationRecord
  # this has many needs to be the literal name of the table
  has_many :fuck_tags_fuck_everything
  has_many :photos, :through => :fuck_tags_fuck_everything
end

app/models/user.rb
require ('./app/models/application_record')

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :photos

  # attr_accessor :username

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    @user = current_user
    @photo = Photo.new
    render :new
  end

  def index
    @photos = current_user.photos
    render :index
  end

  def create
    # relies on the {:multipart => true} section of new.html.erb
    @user = current_user
    title = params[:title]
    caption = params[:caption]
    @photo = @user.photos.new(:title => title, :caption => caption)
    @photo.image_file.attach(params[:image])
    @photo.save
    redirect_to user_photos_path(@user)
  end

  def update
    new_title = params[:title]
    new_caption = params[:caption]
    @photo = Photo.find_by_id(params[:id])
    @photo.title = new_title
    @photo.caption = new_caption
    @photo.save
    redirect_to user_photos_path(current_user)
  end

  def edit
    @user = current_user
    @photo = Photo.find_by_id(params[:id])
    render :edit
  end

  def destroy
    @photo = Photo.find_by_id(params[:id])
    @photo.destroy
    redirect_to user_photos_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # def show
  #   redirect_to root_path
  # end

  def upload

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @users = User.all
    @featured_users = @users.sample(15)
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.4.1.min.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="jumbotron">
      <h1>Definitely Not Flickr</h1>
      <nav class="">
        <% if !current_user %>
          <%= link_to "Sign Up", new_user_registration_path %>
          |
          <%= link_to "Sign In", new_user_session_path %>
          <span class="nav-item-center"><%= link_to "View All Photos", root_path %></span>
        <% else %>
          <%= current_user.email %>
          |
          <%= link_to "Sign Out", destroy_user_session_path, :method=>"delete" %>
          <span class="nav-item-center"><%= link_to "View All Photos", root_path %></span>

          <%= link_to "My Photos", user_photos_path(current_user), :class=>"nav-item-right" %>
          <span class="nav-item-right">&nbsp|&nbsp </span>
          <%= link_to "Upload", new_user_photo_path(current_user), :class =>"nav-item-right" %>
        <% end %>

      </nav>
    </div>
    <%= yield %>
  </body>
</html>

app/views/photos/edit.html.erb
<div class="photo-card">
  <%= form_tag user_photo_path(@photo), method:"patch" do %>
  <%= label_tag "Title:" %>
  <%= text_field_tag :title, @photo.title %>
  <div class="image-holder">
    <%= image_tag url_for(@photo.image_file) %>
  </div>
  <%= label_tag "Caption:" %>
  <%= text_area_tag :caption, @photo.caption %>
  <div class="photo-card-buttons">
    <%= submit_tag "Save Photo", :class=>"btn btn-primary btn-sm" %>
  </div>
  <% end %>
</div>

app/views/photos/index.html.erb
<% if !@photos.any? %>
  <div class="upload-alert photo-card">
    <h4>Upload some photos!</h4>
    <%= link_to "Upload", new_user_photo_path, :class=>"upload-btn btn btn-info" %>
  </div>
<% end %>

<% @photos.each do |p| %>
  <% if p.image_file.attached? %>
    <div class="photo-card">
      <h3><%= p.title %></h3>
      <p><%= p.caption %></p>
      <div class="image-holder">
        <%= image_tag url_for(p.image_file) %>
      </div>
      <div class="photo-card-buttons">
        <%= link_to "Edit Photo", edit_user_photo_path(current_user, p), :class=>"btn btn-primary btn-sm" %>
        <%= link_to "Delete Photo", "javascript:void(0)", :class=>"btn btn-secondary btn-sm", :id=>"pre-delete" %>
        <%= link_to "Are You Sure?", user_photo_path(current_user, p), :class=>"btn btn-danger btn-sm hidden", :method => "delete", :id=>"confirm-delete" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/photos/new.html.erb
<div class="upload-form">
  <%# multipart => true is some magic thing that allows files to be transferred %>
  <%= form_tag photos_path, {:multipart => true} do %>
    <%= label_tag "Upload file" %>
    <%= file_field_tag :image %>
    <%= label_tag "Title" %>
    <%= text_field_tag :title %>
    <%= label_tag "Photo Caption" %>
    <%= text_area_tag :caption %>
    <%= submit_tag "Upload", :class =>"btn btn-primary" %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<% if @featured_users.any? %>

  <% @featured_users.each do |u|%>
  <% if u.photos.any? %>
    <% photo = u.photos.all.first %>

      <div class="photo-card">
        <h3><%= photo.title %></h3>
        <p>Taken by: <%= photo.user.username %></p>
        <div class="image-holder">
          <%= image_tag url_for(photo.image_file) %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>